apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-ingress-operator
  namespace: openshift-cloud-ingress-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
