// THIS FILE IS GENERATED BY BOILERPLATE. DO NOT EDIT.
//go:build integration
// +build integration

package osde2etests

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"path/filepath"
	"testing"
)

const (
	testResultsDirectory = "/test-run-results"
	jUnitOutputFilename  = "junit-example-addon.xml"
)

// Test entrypoint. osde2e runs this as a test suite on test pod.
func CloudIngressOperator(t *testing.T) {
	RegisterFailHandler(Fail)

	suiteConfig, reporterConfig := GinkgoConfiguration()
	reporterConfig.JUnitReport = filepath.Join(testResultsDirectory, jUnitOutputFilename)
	RunSpecs(t, "Cloud Ingress Operator", suiteConfig, reporterConfig)

}
