// THIS FILE IS GENERATED BY BOILERPLATE. DO NOT EDIT.
//go:build osde2e
// +build osde2e

package osde2etests

import (
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// Test entrypoint. osde2e runs this as a test suite on test pod.
func TestCloudIngressOperator(t *testing.T) {
	RegisterFailHandler(Fail)

	RunSpecs(t, "Cloud Ingress Operator")
}
