// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloudclient/gcp/gcp.go

// Package mock_gcp is a generated GoMock package.
package gcp

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	compute "google.golang.org/api/compute/v1"
)

// MockGCPInterface is a mock of GCPInterface interface.
type MockGCPInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGCPInterfaceMockRecorder
}

// MockGCPInterfaceMockRecorder is the mock recorder for MockGCPInterface.
type MockGCPInterfaceMockRecorder struct {
	mock *MockGCPInterface
}

// NewMockGCPInterface creates a new mock instance.
func NewMockGCPInterface(ctrl *gomock.Controller) *MockGCPInterface {
	mock := &MockGCPInterface{ctrl: ctrl}
	mock.recorder = &MockGCPInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCPInterface) EXPECT() *MockGCPInterfaceMockRecorder {
	return m.recorder
}

// GetForwardingRuleList mocks base method.
func (m *MockGCPInterface) GetForwardingRuleList() (*compute.ForwardingRuleList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForwardingRuleList")
	ret0, _ := ret[0].(*compute.ForwardingRuleList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForwardingRuleList indicates an expected call of GetForwardingRuleList.
func (mr *MockGCPInterfaceMockRecorder) GetForwardingRuleList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForwardingRuleList", reflect.TypeOf((*MockGCPInterface)(nil).GetForwardingRuleList))
}
