// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cloudclient/gcp/gcp.go

// Package mock_gcp is a generated GoMock package.
package mock_gcp

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	compute "google.golang.org/api/compute/v1"
)

// MockGCPComputeClient is a mock of GCPComputeClient interface.
type MockGCPComputeClient struct {
	ctrl     *gomock.Controller
	recorder *MockGCPComputeClientMockRecorder
}

// MockGCPComputeClientMockRecorder is the mock recorder for MockGCPComputeClient.
type MockGCPComputeClientMockRecorder struct {
	mock *MockGCPComputeClient
}

// NewMockGCPComputeClient creates a new mock instance.
func NewMockGCPComputeClient(ctrl *gomock.Controller) *MockGCPComputeClient {
	mock := &MockGCPComputeClient{ctrl: ctrl}
	mock.recorder = &MockGCPComputeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCPComputeClient) EXPECT() *MockGCPComputeClientMockRecorder {
	return m.recorder
}

// GetForwardingRuleList mocks base method.
func (m *MockGCPComputeClient) GetForwardingRuleList() (*compute.ForwardingRuleList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForwardingRuleList")
	ret0, _ := ret[0].(*compute.ForwardingRuleList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForwardingRuleList indicates an expected call of GetForwardingRuleList.
func (mr *MockGCPComputeClientMockRecorder) GetForwardingRuleList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForwardingRuleList", reflect.TypeOf((*MockGCPComputeClient)(nil).GetForwardingRuleList))
}
