// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/openshift/cloud-ingress-operator/pkg/apis/cloudingress/v1alpha1.ApiScheme":       schema_pkg_apis_cloudingress_v1alpha1_ApiScheme(ref),
		"github.com/openshift/cloud-ingress-operator/pkg/apis/cloudingress/v1alpha1.ApiSchemeSpec":   schema_pkg_apis_cloudingress_v1alpha1_ApiSchemeSpec(ref),
		"github.com/openshift/cloud-ingress-operator/pkg/apis/cloudingress/v1alpha1.ApiSchemeStatus": schema_pkg_apis_cloudingress_v1alpha1_ApiSchemeStatus(ref),
	}
}

func schema_pkg_apis_cloudingress_v1alpha1_ApiScheme(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ApiScheme is the Schema for the apischemes API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift/cloud-ingress-operator/pkg/apis/cloudingress/v1alpha1.ApiSchemeSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift/cloud-ingress-operator/pkg/apis/cloudingress/v1alpha1.ApiSchemeStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/openshift/cloud-ingress-operator/pkg/apis/cloudingress/v1alpha1.ApiSchemeSpec", "github.com/openshift/cloud-ingress-operator/pkg/apis/cloudingress/v1alpha1.ApiSchemeStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cloudingress_v1alpha1_ApiSchemeSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ApiSchemeSpec defines the desired state of ApiScheme",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_cloudingress_v1alpha1_ApiSchemeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ApiSchemeStatus defines the observed state of ApiScheme",
				Type:        []string{"object"},
			},
		},
	}
}
