// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiScheme) DeepCopyInto(out *ApiScheme) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiScheme.
func (in *ApiScheme) DeepCopy() *ApiScheme {
	if in == nil {
		return nil
	}
	out := new(ApiScheme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiScheme) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiSchemeList) DeepCopyInto(out *ApiSchemeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiScheme, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiSchemeList.
func (in *ApiSchemeList) DeepCopy() *ApiSchemeList {
	if in == nil {
		return nil
	}
	out := new(ApiSchemeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiSchemeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiSchemeSpec) DeepCopyInto(out *ApiSchemeSpec) {
	*out = *in
	in.ManagementAPIServerIngress.DeepCopyInto(&out.ManagementAPIServerIngress)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiSchemeSpec.
func (in *ApiSchemeSpec) DeepCopy() *ApiSchemeSpec {
	if in == nil {
		return nil
	}
	out := new(ApiSchemeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiSchemeStatus) DeepCopyInto(out *ApiSchemeStatus) {
	*out = *in
	if in.HistoricConditions != nil {
		in, out := &in.HistoricConditions, &out.HistoricConditions
		*out = make([]HistoricCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiSchemeStatus.
func (in *ApiSchemeStatus) DeepCopy() *ApiSchemeStatus {
	if in == nil {
		return nil
	}
	out := new(ApiSchemeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HistoricCondition) DeepCopyInto(out *HistoricCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	if in.AllowedCIDRBlocks != nil {
		in, out := &in.AllowedCIDRBlocks, &out.AllowedCIDRBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HistoricCondition.
func (in *HistoricCondition) DeepCopy() *HistoricCondition {
	if in == nil {
		return nil
	}
	out := new(HistoricCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementAPIServerIngress) DeepCopyInto(out *ManagementAPIServerIngress) {
	*out = *in
	if in.AllowedCIDRBlocks != nil {
		in, out := &in.AllowedCIDRBlocks, &out.AllowedCIDRBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementAPIServerIngress.
func (in *ManagementAPIServerIngress) DeepCopy() *ManagementAPIServerIngress {
	if in == nil {
		return nil
	}
	out := new(ManagementAPIServerIngress)
	in.DeepCopyInto(out)
	return out
}
